source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MockServer_Example', :exclusive => true do
  pod 'MockServer', :path => '../'
end

target 'MockServer_Tests', :exclusive => true do
  pod 'MockServer', :path => '../'

  
end
